### ISSUE TITLE
Log cost/price per epoch

### ISSUE THREAD

**Issue by mpariente** [lfwa/carbontracker#39] opened 2020-10-07 10:56 UTC
Would it be possible to log the price per epoch and per training, along the equivalent number of kms in car? 
It would be quite informative. 

Thanks

**Comment by lfwa** [comment] 2020-10-07 11:05
Duplicate of #38.

**Closed by lfwa** 2020-10-07 11:05 UTC
Labels: duplicate

**Comment by mpariente** [comment] 2020-10-07 11:29
Sorry about that, didn't see it was created in the first place.
