### ISSUE TITLE
Unable to run CarbonTracker object

### ISSUE THREAD

**Issue by manuelpabloduran** [lfwa/carbontracker#55] opened 2023-06-01 20:19 UTC
We are trying to run the firsts lines of the example and we are having issues with the kernel.
Are we doing anything wrong to set up the object?
See minimum code below and a print of the error that we get. Thanks!

`from carbontracker.tracker import CarbonTracker

max_epochs = 10
tracker = CarbonTracker(epochs=max_epochs)

# Training loop.
for epoch in range(max_epochs):
    tracker.epoch_start()
    
    # Your model training.

    tracker.epoch_end()

# Optional: Add a stop in case of early termination before all monitor_epochs has
# been monitored to ensure that actual consumption is reported.
tracker.stop()`

![kernel_error_carbonTracker](https://github.com/lfwa/carbontracker/assets/110140841/fc395521-24bf-41d6-a846-1d91a41fe74d)

**Comment by lfwa** [comment] 2023-06-02 16:04
It looks like you are getting the `NoComponentsAvailableError()` exception, where **carbontracker** was not able to detect any Intel CPUs supporting the RAPL interface nor NVIDIA GPUs. It therefore cannot track the energy consumption nor carbon emissions of your compute.

What operating system and hardware are you using?

**Comment by manuelpabloduran** [comment] 2023-06-09 18:48
> It looks like you are getting the `NoComponentsAvailableError()` exception, where **carbontracker** was not able to detect any Intel CPUs supporting the RAPL interface nor NVIDIA GPUs. It therefore cannot track the energy consumption nor carbon emissions of your compute.
> 
> What operating system and hardware are you using?

Hi Ifwa thanks for the quick response.

My computer has the following specifications:

Processor: 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz   2.61 GHz
Edition: Windows 11
Operating system: 64-bit operating system, x64-based processor

From what we are reading, with these specifications the CPU should support the RAPL interface, what else could it be?

**Comment by lfwa** [comment] 2023-06-09 19:21
You should not need a GPU if you have a compatible CPU. I think the problem is that the Intel RAPL interface is not available on Windows (at least it was not when we initially developed the package).

We currently only test **carbontracker** on Linux.

**Comment by PedramBakh** [comment] 2023-09-11 16:26
We believe the issue you've encountered is related to a compatibility challenge specific to certain platforms. To streamline our efforts and discussions, we've decided to close this issue. However, we are opening a new, broader issue titled "[Windows Support] Intel, Nvidia, AMD" #59 to address and track compatibility concerns across different hardware on Windows. We invite you to continue the discussion there and share any additional specifics that could help us enhance support. Thanks for your understanding and collaboration.

**Closed as completed by PedramBakh** 2023-09-11 16:26 UTC
Labels: question
