### ISSUE TITLE
WARNING - Epoch duration is too short for a measurement to be collected.

### ISSUE THREAD

**Issue by HishamAbulfeilat** [lfwa/carbontracker#51] opened 2023-01-23 12:01 UTC
Hi, when I run I get a warning , also it is not measuring from CPU as when I put components= "CPU" it says
 No components were available. CarbonTracker supports Intel CPUs with the RAPL interface and NVIDIA GPUs.
And then the kernel dies. 

I am using Jupyter Notebook

Laptop: Lenovo Legion 5
            RTX 3060
            11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
            16 GB RAM

CarbonTracker: The following components were found: GPU with device(s) NVIDIA GeForce RTX 3060 Laptop GPU.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: 
Actual consumption for 1 epoch(s):
	Time:	0:00:00
	Energy:	0.000000 kWh
	CO2eq:	0.000000 g
	This is equivalent to:
	0.000000 km travelled by car
	
So what is the issue?

Also another question, for the IP Adress API, it has a limit, is there is other API I could use?

**Comment by lfwa** [comment] 2023-01-25 16:23
Hi @HishamAbulfeilat!

Thanks for reporting your issue.

What operating system are you using?
Currently, we rely on Intel RAPL to query the CPU and DRAM power draw, but it may not be available on all OS. I suspect it is not available on Windows and macOS (maybe third-party drivers exist but we have not tested these).

Regarding your second warning `Epoch duration is too short for a measurement to be collected`, this is usually caused by having a too short training loop, e.g. each iteration of your for loop is simply executing too fast for **carbontracker** to collect a measurement. This can happen for all sorts of reason but usually it happens if you have *very* little data, a *very* small model, very efficient hardware, or a combination of these.
If you are not interested in predictions, a simple workaround would be to measure the entire training loop as a single epoch by just running `tracker.epoch_start()` and `tracker.epoch_end()` outside the loop. Otherwise, you have to ensure your epochs are long enough s.t. measurements can be taken, e.g. by treating several epochs as a single one and rewriting your training loop.

And for your last question: at the moment we unfortunately only support retrieving location by IP, but it would be a good idea to also have a string argument, where users can manually set it with e.g. their ISO country code. 
Feel free to create a new issue asking for this as a feature request but I cannot promise any timeline for when we might (or if we even do) get around to implementing it. We also accept pull requests if you wish to give it a try yourself. Just let me know and I will be more than happy to point you in the right direction. It should be pretty straightforward to implement.

**Comment by lfwa** [comment] 2023-01-25 19:03
Sounds good! Good luck with your project :) 

I'll close this issue and mark it as resolved then. Feel free to reopen it or create a new issue, if you experience any other problems.

**Closed** 2023-01-25 19:03 UTC
Labels: question

**Comment by HishamAbulfeilat** [comment] 2023-05-06 12:09
@lfwa , Hi is there a function in the tool that saves the output to CSV file or a function that gets all emissions values because I am trying to get a sum of all emissions values to define a threshold

**Comment by lfwa** [comment] 2023-05-06 12:17
@HishamAbulfeilat We have some log-parsing functions that might help you. Check out [Parsing log files in the README](https://github.com/lfwa/carbontracker#parsing-log-files) and [parser.py](https://github.com/lfwa/carbontracker/blob/master/carbontracker/parser.py). They should help you parse the log files into dictionary objects that you can then work with.

Let me know if that helps or if you need some different functionality :)

**Comment by HishamAbulfeilat** [comment] 2023-05-06 13:13
I am trying to figure out to save the log in csv file instead of txt
can you help?

**Comment by lfwa** [comment] 2023-05-06 13:30
Do you necessarily need to have the logs as csv files?

Depending on how long your experiments span, I would suggest just parsing all of your log data using something along the lines of:
```python
from carbontracker import parser

logs = parser.parse_all_logs(log_dir="./logs/")
```
The `logs` dictionary objects should contain most of what you need including the calculated emissions and measured duration. You might then be able to combine these with the timestamps in the filenames (e.g. `standard_filename`) to figure out what days the different log files are for and thereby retrieve the daily emissions, etc.

**Comment by HishamAbulfeilat** [comment] 2023-05-06 13:38
alright thanks
